name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 600
          record: true
          parallel: true
          group: "material-dashboard-angular2"
          spec: "cypress/e2e/dashboard-tests/**/*"
          config-file: cypress.config.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
